parameters:

    #
    # Entities
    #
    elcodi.core.referral_program.entity.referral_hash.class: Elcodi\ReferralProgramBundle\Entity\ReferralHash
    elcodi.core.referral_program.entity.referral_line.class: Elcodi\ReferralProgramBundle\Entity\ReferralLine
    elcodi.core.referral_program.entity.referral_rule.class: Elcodi\ReferralProgramBundle\Entity\ReferralRule

    #
    # Model
    #
    elcodi.core.referral_program.model.invitation.class: Elcodi\ReferralProgramBundle\Model\Invitation
    elcodi.core.referral_program.model.invitation_bag.class: Elcodi\ReferralProgramBundle\Model\InvitationBag

    #
    # Services
    #
    elcodi.core.referral_program.services.referral_program_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralProgramManager
    elcodi.core.referral_program.services.referral_hash_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralHashManager
    elcodi.core.referral_program.services.referral_route_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralRouteManager
    elcodi.core.referral_program.services.referral_coupon_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralCouponManager
    elcodi.core.referral_program.services.referral_rule_manager.class: Elcodi\ReferralProgramBundle\Services\ReferralRuleManager

    #
    # Generators
    #
    elcodi.core.referral_program.generator.hash_generator.class: Elcodi\ReferralProgramBundle\Generator\ReferralHashGenerator

    #
    # Form Types
    #
    elcodi.core.user.form_types.referralrule.class: Elcodi\ReferralProgramBundle\Form\Type\ReferralRuleType
    elcodi.core.user.form_types.referralline.class: Elcodi\ReferralProgramBundle\Form\Type\ReferralLineType
    elcodi.core.user.form_types.referralhash.class: Elcodi\ReferralProgramBundle\Form\Type\ReferralHashType

    #
    # Routes
    #
    elcodi.core.referral_program.routes.loader.class: Elcodi\ReferralProgramBundle\Router\ReferralProgramRoutesLoader

    #
    # EventListeners
    #
    elcodi.core.referral_program.event_listener.referral_program_event_listener.class: Elcodi\ReferralProgramBundle\EventListener\ReferralProgramEventListener

    #
    # Factories
    #
    elcodi.core.referral_program.factory.referralrule.class: Elcodi\ReferralProgramBundle\Factory\ReferralRuleFactory
    elcodi.core.referral_program.factory.referralline.class: Elcodi\ReferralProgramBundle\Factory\ReferralLineFactory
    elcodi.core.referral_program.factory.referralhash.class: Elcodi\ReferralProgramBundle\Factory\ReferralHashFactory
    elcodi.core.referral_program.factory.invitation.class: Elcodi\ReferralProgramBundle\Factory\InvitationFactory
    elcodi.core.referral_program.factory.invitationbag.class: Elcodi\ReferralProgramBundle\Factory\InvitationBagFactory
