services:

    #
    # EventListeners
    #
    elcodi.core.referral_program.event_listener.referral_program_event_listener:
        class: %elcodi.core.referral_program.event_listener.referral_program_event_listener.class%
        arguments:
            referral_coupon_manager: @elcodi.core.referral_program.services.referral_coupon_manager
            order_coupon_manager: @elcodi.core.cart_coupon.services.order_coupon_manager
            request_stack: @request_stack
        tags:
            - { name: kernel.event_listener, event: user.register, method: onCustomerRegister }
            - { name: kernel.event_listener, event: order.postcreated, method: onCustomerPurchase }
