services:

    #
    # Services
    #
    elcodi.referral_program:
        alias: elcodi.core.referral_program.services.referral_program_manager

    elcodi.core.referral_program.services.referral_program_manager:
        class: %elcodi.core.referral_program.services.referral_program_manager.class%
        arguments:
            event_dispatcher: @event_dispatcher
            referral_rule_repository: @=service("doctrine.orm.entity_manager").getRepository(parameter("elcodi.core.referral_program.entity.referral_rule.class"))
            referral_line_repository: @=service("doctrine.orm.entity_manager").getRepository(parameter("elcodi.core.referral_program.entity.referral_line.class"))
            entity_manager: @doctrine.orm.default_entity_manager
            referral_route_manager: @elcodi.core.referral_program.services.referral_route_manager
            referral_hash_manager: @elcodi.core.referral_program.services.referral_hash_manager
            referral_line_factory: @elcodi.core.referral_program.factory.referralline
            invitation_bag_factory: @elcodi.core.referral_program.factory.invitationbag
            invitation_factory: @elcodi.core.referral_program.factory.invitation
            customer_repository: @=service("doctrine.orm.entity_manager").getRepository(parameter("elcodi.core.user.entity.customer.class"))
            purge_disabled_lines: %elcodi.core.referral_program.purge_disabled_lines%
            auto_referral_assignment: %elcodi.core.referral_program.auto_referral_assignment%

    elcodi.core.referral_program.services.referral_route_manager:
        class: %elcodi.core.referral_program.services.referral_route_manager.class%
        arguments:
            router: @router
            controller_route_name: %elcodi.core.referral_program.controller_route_name%

    elcodi.core.referral_program.services.referral_hash_manager:
        class: %elcodi.core.referral_program.services.referral_hash_manager.class%
        arguments:
            referral_hash_repository: @=service("doctrine.orm.entity_manager").getRepository(parameter("elcodi.core.referral_program.entity.referral_hash.class"))
            entity_manager: @doctrine.orm.default_entity_manager
            referral_hash_generator: @elcodi.core.referral_program.generator.hash_generator
            referral_hash_factory: @elcodi.core.referral_program.factory.referralhash

    elcodi.core.referral_program.services.referral_coupon_manager:
        class: %elcodi.core.referral_program.services.referral_coupon_manager.class%
        arguments:
            event_dispatcher: @event_dispatcher
            referral_program_manager: @elcodi.core.referral_program.services.referral_program_manager
            entity_manager: @doctrine.orm.default_entity_manager
            coupon_manager: @elcodi.core.coupon.services.coupon_manager
            referral_line_repository: @=service("doctrine.orm.entity_manager").getRepository(parameter("elcodi.core.referral_program.entity.referral_line.class"))
            referral_hash_manager: @elcodi.core.referral_program.services.referral_hash_manager

    elcodi.core.referral_program.services.referral_rule_manager:
        class: %elcodi.core.referral_program.services.referral_rule_manager.class%
        arguments:
            referral_rule_repository: @=service("doctrine.orm.entity_manager").getRepository(parameter("elcodi.core.referral_program.entity.referral_rule.class"))
            entity_manager: @doctrine.orm.default_entity_manager
    #
    # Generators
    #
    elcodi.core.referral_program.generator.hash_generator:
        class: %elcodi.core.referral_program.generator.hash_generator.class%

    #
    # Routes
    #
    elcodi.core.referral_program.routes.loader:
        class: %elcodi.core.referral_program.routes.loader.class%
        arguments:
            controller.route.name: %elcodi.core.referral_program.controller_route_name%
            controller.route: %elcodi.core.referral_program.controller_route%
        tags:
            - { name: routing.loader }
